### ISSUE TITLE
install.sh: Failed to parse latest Minecraft server version from https://s3.amazonaws.com/Minecraft.Download/versions/versions.json

### ISSUE THREAD

**Issue by iScripters** [Thue/rfwadmin#37]
As the title says

**Comment by electrodynatronic** [comment]
Same here.

**Comment by electrodynatronic** [comment]
Note this comment in the versions.json file: 
```
{
    "__comment": "This URL is being phased out! Please update your scripts to check https://launchermeta.mojang.com/mc/game/version_manifest.json instead. Thanks <3 --Dinnerbone",
```
However, simply changing the URL in the install.sh script isn't enough. It seems that whitespace has been stripped from the new release file or something.

get the old file `curl https://s3.amazonaws.com/Minecraft.Download/versions/versions.json`

get the new file `curl https://launchermeta.mojang.com/mc/game/version_manifest.json `
